### ISSUE TITLE
[OTHER] -  Blocks any message wich has .

### ISSUE THREAD

**Issue by qwe123coder** [BeccaLyria/discord-bot#752]
### What would you like to share?

when i send my bugs for ex
```
(node:8172) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'actual' of undefined
    at AlexService.check (D:\EddieBot\dist\alexjs\alex.service.js:33:62)
    at AlexHandler.onMessage (D:\EddieBot\dist\alexjs\alex.handler.js:26:48)
    at DiscordHandlerService.<anonymous> (D:\EddieBot\node_modules\discord-nestjs\dist\packages\core\service\discord-handler.service.js:23:39)
    at Generator.next (<anonymous>)
    at D:\EddieBot\node_modules\discord-nestjs\dist\packages\core\service\discord-handler.service.js:14:71
    at new Promise (<anonymous>)
    at __awaiter (D:\EddieBot\node_modules\discord-nestjs\dist\packages\core\service\discord-handler.service.js:10:12)
    at DiscordHandlerService.callHandler (D:\EddieBot\node_modules\discord-nestjs\dist\packages\core\service\discord-handler.service.js:22:16)
    at OnEventResolver.<anonymous> (D:\EddieBot\node_modules\discord-nestjs\dist\packages\core\resolver\on-event.resolver.js:104:46)
    at Generator.next (<anonymous>)
(node:8172) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without
a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:8172) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
it marks it as link 

### Additional information

it marks Node.js Discord.js and other messages wit a .
 it think .js is a link
for ex ab.js it thinks it is a link

**Comment by nhcarrigan** [comment]
Should just be a quick tweak to the regex. Will address after the migration.

**Comment by qwe123coder** [comment]
cool want me to make a pr for this i will fix it

**Comment by nhcarrigan** [comment]
This is blocked until the migration is complete. :)

**Comment by nhcarrigan** [comment]
This is ready for contribution! Be sure to update your fork if you have an existing one.

**Comment by adityaraute** [comment]
But will it not block all legitimate links as well? And the bot would find it hard to differentiate between the two. The better practice would be to mark those terms as `Discord.js` etc. Which I agree is not sustainable.

Also, why do I see EddieBot?

**Comment by nhcarrigan** [comment]
Becca already has link detection. This issue is a request to modify the regex to not detect `.js`.

**Comment by adityaraute** [comment]
If only for one extension, I think yes can go ahead with it.
